# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

def default_pods
    pod 'Alamofire'
end

target 'mamoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  default_pods

end