# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

def default_pods
    pod 'Alamofire', '~> 4.9.1'
    pod 'NVActivityIndicatorView', '~> 4.8.0'
    pod 'CodableAlamofire'
end

target 'mamoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  default_pods

end
